# Generated by Django 4.2 on 2024-02-06 01:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('de7c9bf9-0d59-4ea8-9814-67ccaca1611c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
