# Generated by Django 4.2 on 2024-02-18 19:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_todo_created_at_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('d8e2ee9c-ab80-4487-ae01-89394a7f323e'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TodoTiming',
            fields=[
                ('uid', models.UUIDField(default=uuid.UUID('d8e2ee9c-ab80-4487-ae01-89394a7f323e'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('timing', models.DateField()),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.todo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
