# Generated by Django 4.2 on 2024-02-18 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_alter_todo_uid_todotiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b7cc4245-045d-4e77-92f7-671f0a2bd12d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todotiming',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('b7cc4245-045d-4e77-92f7-671f0a2bd12d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
